Update 05-b-3300

diff --git a/FMI-tasks/Scripting/05-b-3300 b/FMI-tasks/Scripting/05-b-3300
--- a/FMI-tasks/Scripting/05-b-3300
+++ b/FMI-tasks/Scripting/05-b-3300
@@ -1,2 +1,18 @@
 Да се напише shell скрипт, който чете от стандартния вход имената на 3 файла,
 обединява редовете на първите два (man paste), подрежда ги по азбучен ред и резултата записва в третия файл.
+
+#!/bin/bash
+
+if [ ! $# -eq 3 ];then
+	echo "Invalid number of arguments! "
+	exit 1 
+fi
+
+file1="${1}"
+file2="${2}"
+
+if [ ! -e "${file1}" ] || [ ! -e "${file2}" ];then
+	echo "Something is wrond with files!"
+	exit 1
+fi
+paste "${file1}" "${file2}" | sort > "${3}"
