Update 05-b-3400

diff --git a/FMI-tasks/Scripting/05-b-3400 b/FMI-tasks/Scripting/05-b-3400
--- a/FMI-tasks/Scripting/05-b-3400
+++ b/FMI-tasks/Scripting/05-b-3400
@@ -1,3 +1,13 @@
 Да се напише shell скрипт, който чете от стандартния вход име на файл и 
 символен низ, проверява дали низа се съдържа във файла и извежда на стандартния изход 
 кода на завършване на командата с която сте проверили наличието на низа.
+
+#!/bin/bash
+if [ ! $# -eq 2 ]; then
+	echo "Invalid number of arguments"
+	exit 1
+fi
+FILENAME="${1}"
+STRING="${2}"
+grep -qsF "${STRING}" "${FILENAME}"
+echo $?
